config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/register', to: 'registration#new', as: :send_registration
  get '/verification/:id', to: 'item_verification#new', as: :send_item_verification
  patch '/restaurant/items/:id', to: 'restaurant/items#update', as: :approve_item
  get '/dashboard', to: 'users#show', as: :dashboard

  get '/signup', to: 'emails#new', as: :new_email
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create', as: :logged_in
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/activation/:code', to: 'activation#create', as: :activation

  get '/auth/facebook/callback', to: 'facebooks#create'
  get '/auth/google_oauth2/callback', to: 'googles#create'

  resources :users, only: [:create]
  resources :restaurants
  resources :emails, only: :create
  resources :items, only: [:show]

  resources :restaurants, only: [:show]

  resources :search, only: [:index]

  resources :items do
    collection do
      get :autocomplete
    end
  end

  namespace :default do
    resources :items do
      resources :reviews, only: [:new, :create]
    end

    resources :restaurants do
      resources :items, only: [:new, :create]
    end
  end

  match '*path', to: 'welcome#index', via: :all
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :emails
  has_many :facebooks
  has_many :googles

  validates :restaurant_id, presence: true, if: :restaurant?
  validates_presence_of :role, :auth_type, :registered
  enum role: [:default, :restaurant, :photographer, :critic, :admin]
  enum auth_type: [:email, :facebook, :google]

  def reviewable?(item_id)
    Review.where(item_id: item_id, user: self).empty?
  end

  def restaurant?
    role == "restaurant"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    render locals: { facade: DashboardFacade.new(current_user) }
  end
end

app/views/users/_active.html.erb
<h3>Status: Active</h3>

app/views/users/_inactive.html.erb
<h3>This account has not yet been activated. Please check your email or <%= link_to "re-send email", send_registration_path %>.</h3>

app/views/users/new.html.erb
<div class="user-login">
  <main>
<h1>Register</h1>
  <section>
    <%= form_for @user do |f| %>
      <div >
        <%= f.label :email %>
        <%= f.email_field :email, class: "block col-12 field" %>
      </div>
      <div >
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "block col-12 field" %>
      </div>
      <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "block col-12 field" %>
      </div>
      <div>
        <%= f.label :password %>
        <%= f.password_field :password, class: "block col-12 field" %>
      </div>
      <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "block col-12 field" %>
      </div>
      <%= f.submit 'Create Account', class: "mt2 btn btn-primary mb1 bg-teal" %>
    <% end %>
  </section>
  </main>
</div>

app/views/users/show.html.erb
<div class="card text-center" style="width: 25rem; height: 25rem; margin: 30px;float:left">
  <div class="card-header">
    <h3>Account Details</h3>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= display_name %><h5>
    <p class="card-text"><%= render facade.active? %>
  </div>
</div>
<div  style="margin-top:30px;margin-left:30px;float:left;">
  <div class="card-deck">
    <% facade.reviews.each do |review| %>
      <section id="review-<%= review.id %>">
          <div class="card">

            <div class="card-body" style="text-align:center;">
              <h5 class="card-title"><%= review.title %></h5>
              <p><% review.rating.round.times do %>
                <%= image_tag("ramen-bowl.png", style: 'height:25px ;width:auto;') %>
              <% end %>
              <%= "(#{review.rating.round})" %></p>

              <p class="card-text"><%= review.body %></p>
            </div>

          </div>
          <br>
      </section>
    <% end %>
  </div>
</div>

<% if @current_user.restaurant_id %>
  <h1>Pending Items for <%= Restaurant.find(@current_user.restaurant_id).name %></h1>
  <% facade.pending_items.each do |item| %>
    <div class="row justify-content-center" style="margin-top:30px;margin-left:30px;">
      <br>
      <div class="card-deck">
        <section id="item-<%= item.name %>">
            <div class="card">

              <div class="card-body" style="text-align:center;">
                <h5 class="card-title"><%= item.name %></h5>
                <p class="card-text"><%= item.category.capitalize %></p>
                <p class="card-text">Price: <%= number_to_currency(item.price) %></p>
                <p class="card-text"><%= link_to "Approve Item", approve_item_path(item), method: :patch %></p>
              </div>

            </div>
            <br>
        </section>
      </div>
    </div>
  <% end %>
<% end %>