config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/register', to: 'registration#new', as: :send_registration
  get '/verification/:id', to: 'item_verification#new', as: :send_item_verification
  patch '/restaurant/items/:id', to: 'restaurant/items#update', as: :approve_item
  get '/dashboard', to: 'users#show', as: :dashboard

  get '/signup', to: 'emails#new', as: :new_email
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create', as: :logged_in
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/activation/:code', to: 'activation#create', as: :activation

  get '/auth/facebook/callback', to: 'facebooks#create'
  get '/auth/google_oauth2/callback', to: 'googles#create'

  resources :users, only: [:create]
  resources :restaurants
  resources :emails, only: :create
  resources :items, only: [:show]

  resources :restaurants, only: [:show]

  resources :search, only: [:index]

  resources :items do
    collection do
      get :autocomplete
    end
  end

  namespace :default do
    resources :items do
      resources :reviews, only: [:new, :create]
    end

    resources :restaurants do
      resources :items, only: [:new, :create]
    end
  end

  match '*path', to: 'welcome#index', via: :all
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @items_by_rating = Item.by_avg_rating
    @coordinates = location.coordinates
    @restaurants = Restaurant.near(@coordinates, 5)
  end
end

app/views/welcome/index.html.erb
<%= javascript_include_tag "welcome" %>
<script>
  var restaurants = [];
  document.addEventListener("DOMContentLoaded", function(){
    initMap()
  });
  var markers = [];
  var lat = <%= @coordinates[0] %>;
  var lng = <%= @coordinates[1] %>;
  <% @restaurants.each do |restaurant| %>
    var restaurant = ['<%= restaurant.name %>', <%= restaurant.latitude %>, <%= restaurant.longitude %>, '<%= restaurant.address_1 %>, <%= restaurant.city %>, <%= restaurant.state %> <%= restaurant.zip_code %>', '<%= "/restaurants/#{restaurant.id}" %>']
    restaurants.push(restaurant)
  <% end %>
  document.addEventListener("DOMContentLoaded", function(){
    popout()
  });
</script>

<div class="row justify-content-center" style="margin-top:30px;">
  <div class="card-group">
    <% @items_by_rating.each do |item| %>
    <section id="item-<%= item.id %>">
      <div class="card" style="align:center;">

        <div class="card-img-top" style="float:inherit;">
          <a href="#" class="pop">
            <%= image_tag(item.image, style: "height:230px; max-width: 300px;") %>
          </a>
        </div>

        <div class="card-body" style="text-align:center;">
          <h5 class="card-title"><%= link_to item.name, item_path(item) %></h5>
          <p class="card-text">Price: <%= number_to_currency(item.price) %></p>
          <p class="card-text">Average Rating: <%= item.average_rating.round(1) %></p>
          <% if current_user&.default? && current_user.registered == 'true' && current_user.reviewable?(item.id) %>
            <p class="card-text"><%= link_to "Write a Review", new_default_item_review_path(item) %></p>
          <% end %>
        </div>

        <div class="card-footer" style="text-align:center;">
          <p class="card-text"><small class="text-muted"><%= link_to item.restaurant.name, restaurant_path(item.restaurant) %></small></p>
        </div>

      </div>
      <br>
    </section>
    <% end %>
  </div>
</div>

<div class="index_main">
  <div class="fixed_column">
    <div class="nearby">
      <ul>
        <% @restaurants.each_with_index do |restaurant, i| %>
          <div class="card border-primary mb-3" onclick="showMarker(<%= i %>)" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title" onclick="showMarker(<%= i %>)"><%= restaurant.name %></h5>
              <span style="font-size:60"><%= (restaurant.distance_to(@coordinates)).round(2) %> mi</span>
              <p class="card-text" style="color: blue"><%= restaurant.address_1 %>, <%= restaurant.city %>, <%= restaurant.state %> <%= restaurant.zip_code %></p>
            </div>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
  
  <div class="fluid-column">
    <div id="map" style="width:75%; height:100%;display:inline-block; box-shadow: 0px 0px 2px 0px grey; position: absolute;"></div>
  </div>
</div>

<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
      	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <img src="" class="imagepreview" style="width: 100%;" >
      </div>
    </div>
  </div>
</div>