config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/register', to: 'registration#new', as: :send_registration
  get '/verification/:id', to: 'item_verification#new', as: :send_item_verification
  patch '/restaurant/items/:id', to: 'restaurant/items#update', as: :approve_item
  get '/dashboard', to: 'users#show', as: :dashboard

  get '/signup', to: 'emails#new', as: :new_email
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create', as: :logged_in
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/activation/:code', to: 'activation#create', as: :activation

  get '/auth/facebook/callback', to: 'facebooks#create'
  get '/auth/google_oauth2/callback', to: 'googles#create'

  resources :users, only: [:create]
  resources :restaurants
  resources :emails, only: :create
  resources :items, only: [:show]

  resources :restaurants, only: [:show]

  resources :search, only: [:index]

  resources :items do
    collection do
      get :autocomplete
    end
  end

  namespace :default do
    resources :items do
      resources :reviews, only: [:new, :create]
    end

    resources :restaurants do
      resources :items, only: [:new, :create]
    end
  end

  match '*path', to: 'welcome#index', via: :all
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  validates_presence_of :name,
                        :rating,
                        :latitude,
                        :longitude,
                        :address_1,
                        :city,
                        :state,
                        :zip_code,
                        :phone

  validates :yelp_id, presence: true, uniqueness: true
  has_many :items
  has_many :users

  def num_pending
    items.where(items: {status: 'pending'}).count
  end

  def encoded_address
    URI.escape(address)
  end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def show
    @restaurant = Restaurant.includes(:items).find(params[:id])
  end

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :latitude, :longitude)
    end
end

app/controllers/restaurant/base_controller.rb
class Restaurant::BaseController < ApplicationController
  before_action :require_restaurant

  private

  def require_restaurant
    redirect_to root_path unless current_user.restaurant? && current_user.registered == 'true'
  end
end

app/controllers/restaurant/items_controller.rb
class Restaurant::ItemsController < Restaurant::BaseController
  def update
    item = Item.find(params[:id])
    if item.restaurant_id == current_user.restaurant_id
      item.update_attributes(status: 'verified')
    end
    flash[:notice] = 'This item has been verified!'
    redirect_to dashboard_path
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
    @restaurant = Restaurant.includes(:items).find(params[:id])
  end
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.latitude %></td>
        <td><%= restaurant.longitude %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<%= javascript_include_tag "restaurants" %>
<script>
  document.addEventListener("DOMContentLoaded", function(){
    initMap('<%= @restaurant.name %>', <%=@restaurant.latitude%>, <%=@restaurant.longitude%>, '<%= @restaurant.address_1 %>', '<%= @restaurant.city %>', '<%= @restaurant.state %>', '<%= @restaurant.zip_code %>')
  });
  var address = '<%= @restaurant.address %>';
  document.addEventListener("DOMContentLoaded", function(){
    popout()
  });
</script>

<p id="notice"><%= notice %></p>

<div class='rest_main'>
  <div class='info-card'>
    <div class="card text-center" style="width: 25rem; height: 25rem; margin: 30px;">
      <div class="card-header" style="height: 6rem">
        <h1><%= @restaurant.name %></h1>
      </div>
      <div class="card-body">
        <p class="card-text">Yelp Rating: <%= @restaurant.rating %></p>
        <p class="card-text"><%= @restaurant.address_1 %> <%= @restaurant.address_2  %></p>
        <p class="card-text"><%= @restaurant.city %>, <%= @restaurant.state %> <%= @restaurant.zip_code %></p>
        <p class="card-text">Phone: <%= @restaurant.phone %></p>
        <%= link_to '<button type="button", class="btn">Get Directions</button>'.html_safe, "https://www.google.com/maps/dir/?api=1&destination=#{@restaurant.encoded_address}" %>
        <% if current_user&.default? && current_user.registered == 'true' %>
          <%= button_to "Review a New Item", new_default_restaurant_item_path(@restaurant), method: :get, class: "btn" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="fluid-column">
    <div id="map" style="display:inline-block; box-shadow: 0px 0px 2px 0px grey; margin: 30px 20px 0px 0px;"></div>
  </div>
</div>

<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
      	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <img src="" class="imagepreview" style="width: 100%;" >
      </div>
    </div>
  </div>
</div>

<section class='items' style="display: inline-block">
  <div class="row justify-content-center" style="margin-top: 40px;">
    <div class="card-deck">
      <% @restaurant.items.each do |item| %>
        <% if item.status == 'verified' %>
          <section class='item' id='<%= item.name %>'>
            <div class="card" style="align:center;">

              <div class="card-img-top" style="float:inherit;">
                <a href="#" class="pop">
                  <%= image_tag(item.image, style: "height:240px;") %>
                </a>
              </div>

              <div class="card-body" style="text-align:center;">
                <h5 class="card-title"><%= link_to item.name, item_path(item) %></h5>
                <p class="card-text">Price: <%= number_to_currency(item.price) %></p>
                <p class="card-text">Average Rating: <%= item.average_rating.round(1) %></p>
                <% if current_user&.default? && current_user.registered == 'true' && current_user.reviewable?(item.id) %>
                  <p class="card-text"><%= link_to "Write a Review", new_default_item_review_path(item) %></p>
                <% end %>
              </div>
            </div>
          </section>
        <% end %>
      <% end %>
    </div>
  </div
</section>